Feat/component
vtex-apps/sticky-layout pull request #1
Opened 2019-07-09 20:07 UTC by jgfidelis

https://fidelis--delivery.myvtex.com/pizza-pepperoni/p

2019-07-09 20:47 UTC, lbebber requested changes

2019-07-09 20:47 UTC, lbebber commented on react/index.tsx
> +enum POSITIONS {
I think it's more standard for enums to have CapitalizedCamelCase

2019-07-09 20:47 UTC, lbebber commented on react/index.tsx
> +import styles from './styles.css'
nit, but move styles to the bottom of the imports in a separate group

2019-07-09 20:47 UTC, lbebber commented on react/index.tsx
> +  BOTTOM = 'BOTTOM',
also the actual value of the enum should be lower case I think

2019-07-09 20:47 UTC, lbebber commented on react/index.tsx
> +      container.current.style.transform = `translateY(${newTop}px)`
it's a hack, but `translate3d(x,y,z)` has generally better performance (bc it forces the element to be in a separate composition layer)

2019-07-09 20:55 UTC, klzns requested changes

2019-07-09 20:55 UTC, klzns commented on README.md
> +"store.product": {
```suggestion
  "store.product": {
```

2019-07-09 20:55 UTC, klzns commented on README.md
> +```
```suggestion
```js
```

2019-07-09 20:55 UTC, klzns commented on README.md
> +}
```suggestion

```

2019-07-09 20:55 UTC, klzns commented on manifest.json
> +  "title": "Modal",
```suggestion
  "title": "Sticky Layout",
```

2019-07-09 20:55 UTC, klzns commented on react/.eslintrc
> +  "extends": "vtex",
Setup the right eslint
https://docs.google.com/document/d/1ePi5Mn3pe1dOorKrMtC-MclBDiIDimVzf0Uj61W8lA4/edit

2019-07-09 20:55 UTC, klzns commented on react/index.tsx
> +//@ts-ignore
Add definition for css files 
https://github.com/vtex-apps/base-store-component/blob/master/react/typings/css.d.ts

2019-07-09 20:55 UTC, klzns commented on react/index.tsx
> +  const handleScroll = () => {
This function should be inside the `useEffect`

2019-07-09 20:55 UTC, klzns commented on react/index.tsx
> +    <Fragment>
Remove Fragment

2019-07-09 20:55 UTC, klzns commented on react/tsconfig.json
> +    "noUnusedParameters": true,
Check if it's right 
https://docs.google.com/document/d/1ePi5Mn3pe1dOorKrMtC-MclBDiIDimVzf0Uj61W8lA4/edit#heading=h.8db4tllwjh7n

2019-07-09 20:55 UTC, jgfidelis commented on README.md
> +```
its a json :P

2019-07-09 21:07 UTC, lbebber commented on README.md
> +Passing the prop `"position": "BOTTOM"` in your blocks.json, makes its children stick to the bottom of its view, while it should be hidden and once it reaches the position it should be, it stops and
```suggestion
Passing the prop `"position": "bottom"` in your blocks.json, makes its children stick to the bottom of its view, while it should be hidden and once it reaches the position it should be, it stops and stays there.
```

2019-07-10 17:21 UTC, klzns approved these changes

2019-07-10 17:29 UTC, merged