Add support for 'top' sticky and refactor
vtex-apps/sticky-layout pull request #4
Opened 2019-08-25 15:08 UTC by victorhmp

#### What did you change?

Added support for `position: 'top'` on `sticky-layout` and also refactor the app to contain and use the logic previously at `vtex.store-header` to calculate offsets and make items stick using the `position: 'sticky'` CSS property.

Now this app also exports `StickyRow` and `StickyRows` components, that are used right now by the `vtex.store-header` app.

#### Why? \*

So that users can use the `vtex.sticky-layout` app in a more flexible way, in different scenarious.
An example is our Store Header, which now uses `sticky-layout` to stick a `flex-layout.row` to the top of the page.

#### How to test it? \*

Take a look at this workspace: https://victorhmp--storecomponents.myvtex.com/

The Header component is using `sticky-layout` with `position: 'top'`, while the product page is using a Buy Button wrapped by a `sticky-layout` with `position: 'bottom'`.

#### Related to / Depends on?

This will only work with https://github.com/vtex-apps/render-runtime/pull/378 released.

#### Types of changes \*

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical improvements

2019-08-27 13:34 UTC, jgfidelis requested changes

2019-08-27 13:34 UTC, jgfidelis commented on react/hooks/useScroll.tsx
> +  if (position === Positions.TOP)
put `{}` in the `if`please

2019-08-27 14:15 UTC, victorhmp commented on react/hooks/useScroll.tsx
> +  if (position === Positions.TOP)
Done!

2019-10-01 13:11 UTC, victorhmp commented
Closing this for now.

2019-10-01 13:11 UTC, closed without merging